### ISSUE TITLE
Errors when using render or data for fountain file converted from FDX

### ISSUE THREAD

**Issue by Britman72** [qxoko/meander#4]
Using meander on Apple M2.

meander convert file.fdx - works fine and creates a .fountain file.

Then when running meander against the newly created .fountain file using either render or data option, gives the following error:

```
meander render file.fountain or..
meander data file.fountain

panic: runtime error: index out of range [3891] with length 3891

goroutine 1 [running]:
main.syntax_parser(0x140000940a0, 0x140000ebdc8, {0x14000154000, 0x1b813})
	github.com/qxoko/meander/source/parser.go:692 +0x21f8
main.command_render(0x140000940a0)
	github.com/qxoko/meander/source/command_render.go:57 +0x90
main.main()
	github.com/qxoko/meander/source/meander.go:35 +0x40
```

For reference, there are 3894 lines in the converted .fountain file.

If I add an extra line at the end with any character such as ".", then it works fine.

**Comment by qxoko** [comment]
Thanks for reporting this one!

I was able to reproduce it and fix it.  Look out for the v0.2.2 release later today with a couple of other bug fixes in it.
